CREATE TABLE _user (
    id VARCHAR(28) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(60) NOT NULL,
    phone VARCHAR(12) UNIQUE NOT NULL,
    is_verified BOOL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT  CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT  CURRENT_TIMESTAMP
);

SELECT * FROM _user;

CREATE TRIGGER trigger_accounts_update
    BEFORE UPDATE ON _user
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at();